spring.application.name=pronostico
springdoc.swagger-ui.path=pronostico
spring.jackson.time-zone=America/Argentina/Buenos_Aires
stm.wtf.aws.repo=https://smn-ar-wrf.s3.amazonaws.com/DATA/WRF/DET/
stm.wtf.aws.saveDir=/app/downloads/